- name: Send success email
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: smtp.gmail.com
    server_port: 465
    username: ${{ secrets.EMAIL_USERNAME }}
    password: ${{ secrets.EMAIL_PASSWORD }}
    subject: "✅ Build completed"
    to: jurasz.jan@example.com
    from: GitHub Actions <jurasz.jan@example.com>
    body: |
      Aplikacja została pomyślnie zbudowana.
      Frontend: ./frontend
      Backend: ./backend
