### 
POST http://localhost:8081/categories
Content-Type: application/json

{
  "name": "Demo112212121"
}

###


POST http://localhost:8081/products
Content-Type: application/json

{
  "name": "Laptopsasa",
  "price": 4200,
  "categoryID": 1
}

###


GET http://localhost:8081/products

###

GET http://localhost:8081/products?category=1&minPrice=100000

###


POST http://localhost:8081/carts
Content-Type: application/json

{
  "userID": 1
}

###


GET http://localhost:8081/categories
