services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules       # ważne dla uniknięcia konfliktów node_modules z hostem
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true  # potrzebne dla hot reload w Vite w Dockerze
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    command: sh -c "npm install && node index.js"
